"""
qa_assistant.py — Source-Grounded Q&A Assistant  v2.5

Provides a conversational Q&A interface where every answer is:
  1. Generated by Groq with the retrieved context injected.
  2. Grounded in the validated sources from the last discovery session.
  3. Annotated with clean citations ([1] or superscript) linked to PMIDs / URLs.
  4. Refused if the answer cannot be grounded (hallucination guard).

Changes vs v2.4:
  - Removed Ollama fallback; now exclusively uses Groq.
  - Simplified retry logic (no skipping to alternate provider).
  - Updated error messages to reflect only Groq.
"""

from __future__ import annotations

import asyncio
import re
import textwrap
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple
from urllib.parse import urlparse

from loguru import logger

from models import ACPResponse


# =============================================================================
# CONSTANTS
# =============================================================================

MAX_HISTORY_TURNS:  int   = 6
MAX_CONTEXT_CHUNKS: int   = 8
CHUNK_TEXT_LIMIT:   int   = 600
CHARS_PER_TOKEN:    float = 3.5
MAX_PROMPT_TOKENS:  int   = 3_500

# Retry config for Groq
RETRY_ATTEMPTS:      int   = 3
RETRY_BASE_DELAY:    float = 2.0    # seconds — generic back-off

# Collections to search (same two the retriever uses)
QA_COLLECTIONS: List[str] = ["texts_collection", "pdfs_collection"]

USE_SUPERSCRIPT: bool = True


# =============================================================================
# PROMPTS
# =============================================================================

QA_SYSTEM_PROMPT = """\
You are a rigorous biomedical research assistant. You ONLY answer from the
provided context sources.

IMPORTANT CITATION RULES:
- Place citations at the END of a sentence or list item, not in the middle.
- For a list item that uses multiple sources, write: "• Raf [1][2][3]"
- Never put a citation inside a word or between words without a space.
- Use markdown for clarity (bold key terms, bullet points for lists).
- If the answer is not in the sources, reply ONLY:
  "INSUFFICIENT_CONTEXT: <brief explanation>"
- Keep answers concise (≤250 words unless the question requires more).
- Never fabricate PMIDs, DOIs, or drug names.
- EVERY factual claim MUST be followed by at least one [N] citation.
"""

QA_USER_TEMPLATE = """\
SOURCES:
{sources}

CONVERSATION HISTORY:
{history}

QUESTION: {question}

Answer with inline citations [N] after every factual claim. If you cannot \
answer from these sources, respond with INSUFFICIENT_CONTEXT.
"""


# =============================================================================
# CUSTOM EXCEPTIONS
# =============================================================================

class RateLimitError(Exception):
    """Raised when Groq returns HTTP 429 so that the retry loop can act."""
    def __init__(self, retry_after: float = RETRY_BASE_DELAY):
        self.retry_after = retry_after
        super().__init__(f"Groq rate-limited; retry after {retry_after}s")


# =============================================================================
# DATA MODELS
# =============================================================================

@dataclass
class Reference:
    index:  int
    title:  str
    url:    str
    pmid:   Optional[str] = None
    doi:    Optional[str] = None
    domain: str = field(default="")

    def __post_init__(self) -> None:
        if not self.domain and self.url:
            try:
                self.domain = urlparse(self.url).netloc
            except Exception:
                self.domain = ""

    def __str__(self) -> str:
        label = self.title
        if self.pmid:
            label += f" (PMID:{self.pmid})"
        if self.url:
            return f"[{self.index}] [{label}]({self.url})"
        return f"[{self.index}] {label}"


@dataclass
class QAAnswer:
    question:     str
    text:         str               # raw [N] markers preserved for programmatic use
    references:   List[Reference]
    grounded:     bool = True
    sources_used: int  = 0
    provider:     str  = ""         # always "groq" when successful

    def to_text(self, superscript: bool = USE_SUPERSCRIPT) -> str:
        """
        Render for display.  Superscript conversion happens HERE only so that
        the raw `text` field always keeps [N] markers.
        """
        body = _to_superscript_all(self.text) if superscript else self.text

        if not self.grounded:
            return body + (
                "\n\n⚠ *This answer could not be fully grounded in the "
                "available sources.*"
            )

        if self.references:
            ref_block = "\n\n".join(str(r) for r in self.references)
            provider_note = (
                f"\n\n*Answered by: {self.provider}*" if self.provider else ""
            )
            return body + f"\n\n**References:**\n{ref_block}" + provider_note

        return body


# =============================================================================
# UTILITY — pure functions, easy to unit-test
# =============================================================================

def _to_superscript_all(text: str) -> str:
    """Replace every [N] with Unicode superscript digits (works for N ≥ 10)."""
    sup = str.maketrans("0123456789", "⁰¹²³⁴⁵⁶⁷⁸⁹")
    return re.sub(r"\[(\d+)\]", lambda m: m.group(1).translate(sup), text)


def _estimate_tokens(text: str) -> int:
    return int(len(text) / CHARS_PER_TOKEN)


def _is_refusal(text: str) -> bool:
    """Return True if the model output indicates it cannot answer from sources."""
    if not text:
        return False
    text_lower = text.lower()
    refusal_patterns = [
        r"cannot find a reliable answer",
        r"do not mention",
        r"not mentioned in the (provided )?sources",
        r"insufficient context",
        r"no information (about|on)",
        r"the sources do not contain",
    ]
    return any(re.search(p, text_lower) for p in refusal_patterns)


def _format_sources(chunks: List[Dict[str, Any]]) -> str:
    lines = []
    for i, c in enumerate(chunks, 1):
        pmid_str = f" | PMID:{c['pmid']}" if c.get("pmid") else ""
        lines.append(
            f"[{i}] {c['title']}{pmid_str}\n"
            f"URL: {c['url']}\n"
            f"{c['text']}\n"
        )
    return "\n---\n".join(lines)


def _parse_citations(
    raw: str, chunks: List[Dict[str, Any]]
) -> Tuple[str, List[Reference]]:
    """
    Extract [N] markers from the model output and build a deduplicated
    Reference list.  Out-of-range indices are logged and skipped.
    """
    found = sorted(set(int(m) for m in re.findall(r"\[(\d+)\]", raw)))
    references: List[Reference] = []
    for idx in found:
        if 1 <= idx <= len(chunks):
            c = chunks[idx - 1]
            references.append(Reference(
                index=idx,
                title=c.get("title", "Untitled"),
                url=c.get("url", ""),
                pmid=c.get("pmid"),
                doi=c.get("doi"),
            ))
        else:
            logger.warning(
                f"Model cited [{idx}] but only {len(chunks)} sources provided — "
                "possible hallucinated citation index."
            )
    return raw, references


# =============================================================================
# LOW-LEVEL GROQ HELPERS (with retries, no fallback)
# =============================================================================

async def _call_groq_chat(groq_client, prompt: str, **kwargs) -> str:
    """
    Thin async wrapper around GroqClient.chat() that converts silent failures
    into proper exceptions so the retry loop can act on them.
    """
    if getattr(groq_client, "_unavailable", False):
        raise RuntimeError("Groq permanently unavailable (auth error)")

    result = await groq_client.chat(prompt, **kwargs)

    if result is None or result == "":
        raise RateLimitError(RETRY_BASE_DELAY)

    if result.startswith("__RATE_LIMIT__:"):
        try:
            real_delay = float(result.split(":", 1)[1])
        except (IndexError, ValueError):
            real_delay = RETRY_BASE_DELAY
        raise RateLimitError(real_delay)

    return result


async def _retry_groq(groq_client, prompt: str, **kwargs) -> str:
    """
    Retry Groq up to RETRY_ATTEMPTS times.
    """
    last_exc: Exception = RuntimeError("No attempts made")

    for attempt in range(1, RETRY_ATTEMPTS + 1):
        try:
            return await _call_groq_chat(groq_client, prompt, **kwargs)

        except RateLimitError as exc:
            last_exc = exc
            wait = exc.retry_after

            if attempt < RETRY_ATTEMPTS:
                logger.warning(
                    f"Groq rate-limit attempt {attempt}/{RETRY_ATTEMPTS} — "
                    f"waiting {wait:.0f}s"
                )
                await asyncio.sleep(wait)

        except RuntimeError:
            raise  # permanent auth failure

        except Exception as exc:
            last_exc = exc
            delay = RETRY_BASE_DELAY * (2 ** (attempt - 1))
            if attempt < RETRY_ATTEMPTS:
                logger.warning(
                    f"Groq attempt {attempt}/{RETRY_ATTEMPTS} failed: {exc} — "
                    f"retrying in {delay:.1f}s"
                )
                await asyncio.sleep(delay)

    raise last_exc


# =============================================================================
# QA ASSISTANT
# =============================================================================

class QAAssistant:
    """
    Source-grounded Q&A assistant for drug target discovery sessions.

    LLM: Groq (primary, with retries). No fallback to other providers.

    Context retrieval priority:
      1. Qdrant hybrid_search() across texts_collection + pdfs_collection.
      2. In-process cosine semantic search.
      3. Score-sorted fallback.
    """

    def __init__(self, groq_client, embed_service, qdrant_mgr):
        self._groq:    Any                   = groq_client
        self._embed:   Any                   = embed_service
        self._qdrant:  Any                   = qdrant_mgr
        self._context: List[Dict[str, Any]]  = []
        self._history: List[Tuple[str, str]] = []

    # =========================================================================
    # SESSION MANAGEMENT
    # =========================================================================

    def load_session(self, response: ACPResponse) -> None:
        """
        Load context from a completed ACPResponse.
        Flattens payload items and enriches with target/chemical summaries.
        """
        self._context = []
        self._history = []

        # ── Source documents ──────────────────────────────────────────────────
        for items in response.payload.values():
            for item in items:
                self._context.append({
                    "title": item.get("title", "Untitled"),
                    "url":   item.get("source_url", ""),
                    "pmid":  item.get("pmid"),
                    "doi":   item.get("doi"),
                    "text":  item.get("content", "")[:CHUNK_TEXT_LIMIT],
                    "score": item.get("validation_score", 0.0),
                })

        # ── Target summaries ──────────────────────────────────────────────────
        for t in response.targets or []:
            summary = (
                f"Drug target: {t.get('gene','?')} ({t.get('protein','')}) "
                f"| Disease: {t.get('disease_context','?')} "
                f"| UniProt: {t.get('uniprot_id','?')} "
                f"| Mutations: {', '.join(t.get('mutations', []))} "
                f"| Druggability: {t.get('druggability_notes','')[:120]} "
                f"| PubMed freq score: {t.get('pubmed_frequency_score','?')} "
                f"| Top pathway: {t.get('top_pathway','?')}"
            )
            self._context.append({
                "title": f"Target: {t.get('gene','?')}",
                "url":   f"https://uniprot.org/uniprot/{t.get('uniprot_id','')}",
                "pmid":  (t.get("supporting_pmids") or [None])[0],
                "doi":   None,
                "text":  summary[:CHUNK_TEXT_LIMIT],
                "score": 0.95,
            })

        # ── Chemical summaries ────────────────────────────────────────────────
        for c in response.chemicals or []:
            acts = c.get("bioactivities", [])
            act_str = "; ".join(
                f"{a.get('target','?')} {a.get('assay_type','?')} "
                f"{a.get('relation','=')}{a.get('value','?')} {a.get('units','?')}"
                for a in acts[:3]
            )
            summary = (
                f"Chemical: {c.get('name','?')} | Formula: {c.get('formula','?')} "
                f"| MW: {c.get('mol_weight','?')} Da "
                f"| Phase: {c.get('phase','?')} "
                f"| Class: {c.get('drug_class','?')} "
                f"| Bioactivity: {act_str or 'none'}"
            )
            self._context.append({
                "title": f"Chemical: {c.get('name','?')}",
                "url":   c.get("pubchem_url", ""),
                "pmid":  (c.get("supporting_pmids") or [None])[0],
                "doi":   None,
                "text":  summary[:CHUNK_TEXT_LIMIT],
                "score": 0.90,
            })

        logger.info(
            f"QAAssistant: loaded {len(self._context)} context chunks "
            f"from session {response.session_id}"
        )

    # =========================================================================
    # GROQ CALL (without fallback)
    # =========================================================================

    async def _call_groq(self, prompt: str, **kwargs) -> str:
        """
        Call Groq with retries. Raises RuntimeError on final failure.
        """
        return await _retry_groq(self._groq, prompt, **kwargs)

    # =========================================================================
    # ASK
    # =========================================================================

    async def ask(self, question: str) -> QAAnswer:
        if not self._context:
            return QAAnswer(
                question=question,
                text="No discovery session is loaded. Run a query first.",
                references=[],
                grounded=False,
            )

        # ── Retrieve relevant context ─────────────────────────────────────────
        relevant = await self._select_context(question)
        if not relevant:
            relevant = sorted(
                self._context, key=lambda x: x["score"], reverse=True
            )[:MAX_CONTEXT_CHUNKS]

        # ── Build prompt ──────────────────────────────────────────────────────
        source_block  = _format_sources(relevant)
        history_block = self._format_history()
        prompt = QA_USER_TEMPLATE.format(
            sources=source_block,
            history=history_block,
            question=question,
        )

        # ── Token budget guard ────────────────────────────────────────────────
        estimated = _estimate_tokens(QA_SYSTEM_PROMPT + prompt)
        if estimated > MAX_PROMPT_TOKENS:
            logger.warning(
                f"Prompt estimated at ~{estimated} tokens "
                f"(limit {MAX_PROMPT_TOKENS}). Consider reducing context."
            )

        # ── Call Groq ─────────────────────────────────────────────────────────
        raw = ""
        provider = ""
        all_failed = False

        try:
            raw = await self._call_groq(
                prompt,
                max_tokens=600,
                temperature=0.0,
                system_prompt=QA_SYSTEM_PROMPT,
            )
            provider = "groq"
            logger.info("QAAssistant: answer provided by Groq")
        except RuntimeError as exc:
            all_failed = True
            logger.error(f"QAAssistant: Groq failed after retries: {exc}")
        except Exception as exc:
            all_failed = True
            logger.error(f"QAAssistant: unexpected Groq error: {exc}")

        # ── Hallucination guard and refusal detection ─────────────────────────
        grounded   = True
        references: List[Reference] = []
        answer_text = ""

        refusal_detected = (
            not raw
            or raw.strip().startswith("INSUFFICIENT_CONTEXT")
            or _is_refusal(raw)
        )

        if refusal_detected:
            grounded = False

            if all_failed:
                reason = (
                    "The Groq cloud service is currently unavailable after multiple retries.\n\n"
                    "**To fix this:**\n"
                    "- Wait a few minutes (rate limit) or upgrade your plan at "
                    "https://console.groq.com\n"
                    "- Check your API key and internet connection."
                )
            elif raw and raw.strip().startswith("INSUFFICIENT_CONTEXT:"):
                reason = raw.replace("INSUFFICIENT_CONTEXT:", "").strip()
            elif raw and _is_refusal(raw):
                reason = (
                    "The model indicated it could not find the information "
                    "in the loaded sources."
                )
            else:
                reason = "The LLM did not return a usable response."

            answer_text = (
                "I cannot find a reliable answer to this question in the "
                f"available sources.\n\n{reason}\n\n"
                "You may want to run a more specific query or check the "
                "original sources directly."
            )
            references = []

        else:
            answer_text, references = _parse_citations(raw, relevant)

            if not references:
                logger.warning(
                    "QAAssistant: model produced an answer with zero citations — "
                    "marking as ungrounded."
                )
                grounded = False

        # ── Update history ────────────────────────────────────────────────────
        self._history.append((question, answer_text))
        if len(self._history) > MAX_HISTORY_TURNS:
            self._history = self._history[-MAX_HISTORY_TURNS:]

        return QAAnswer(
            question=question,
            text=answer_text,
            references=references,
            grounded=grounded,
            sources_used=len(relevant),
            provider=provider,
        )

    def clear_history(self) -> None:
        """Reset conversation history (keep loaded session context)."""
        self._history = []

    def context_count(self) -> int:
        return len(self._context)

    # =========================================================================
    # PRIVATE — CONTEXT SELECTION
    # =========================================================================

    async def _select_context(
        self, question: str
    ) -> List[Dict[str, Any]]:
        """
        Three-tier retrieval:
          1. Qdrant hybrid_search() — searches texts + pdfs, merges by score.
          2. In-process semantic search with parallel embeddings.
          3. Score-sorted fallback (no embedding).
        """
        if self._qdrant is not None:
            try:
                results = await self._qdrant_search(question)
                if results:
                    logger.debug(
                        f"QAAssistant: Qdrant returned {len(results)} chunks"
                    )
                    return results
            except Exception as exc:
                logger.debug(
                    f"QAAssistant: Qdrant search failed: {exc} — falling back"
                )

        try:
            results = await self._semantic_search(question)
            if results:
                logger.debug(
                    f"QAAssistant: semantic search returned {len(results)} chunks"
                )
                return results
        except Exception as exc:
            logger.debug(
                f"QAAssistant: semantic search failed: {exc} — using score order"
            )

        logger.debug("QAAssistant: using score-sorted fallback")
        return sorted(
            self._context, key=lambda x: x["score"], reverse=True
        )[:MAX_CONTEXT_CHUNKS]

    async def _qdrant_search(self, question: str) -> List[Dict[str, Any]]:
        q_emb = await self._embed.embed_text_safe(question)
        if q_emb is None:
            raise ValueError("null question embedding")

        tasks = [
            self._qdrant.hybrid_search(
                query_vector=q_emb,
                collection_name=col,
                top_k=MAX_CONTEXT_CHUNKS,
            )
            for col in QA_COLLECTIONS
        ]
        per_collection: List[List[Dict]] = await asyncio.gather(
            *tasks, return_exceptions=True
        )

        merged: List[Dict[str, Any]] = []
        for col, result in zip(QA_COLLECTIONS, per_collection):
            if isinstance(result, Exception):
                logger.debug(f"QAAssistant: Qdrant search on {col} failed: {result}")
                continue
            for hit in result:
                payload = hit.get("payload", {})
                merged.append({
                    "title": payload.get("title", "Untitled"),
                    "url":   payload.get("source_url", ""),
                    "pmid":  payload.get("pmid"),
                    "doi":   payload.get("doi"),
                    "text":  payload.get("content", "")[:CHUNK_TEXT_LIMIT],
                    "score": hit.get("score", 0.0),
                })

        if not merged:
            raise ValueError("Qdrant returned no results from any collection")

        seen: Dict[Tuple[str, str], Dict] = {}
        for item in merged:
            key = (item["url"], item["title"])
            if key not in seen or item["score"] > seen[key]["score"]:
                seen[key] = item

        return sorted(seen.values(), key=lambda x: x["score"], reverse=True)[
            :MAX_CONTEXT_CHUNKS
        ]

    async def _semantic_search(self, question: str) -> List[Dict[str, Any]]:
        import numpy as np
        from sklearn.metrics.pairwise import cosine_similarity

        q_emb = await self._embed.embed_text_safe(question)
        if q_emb is None:
            raise ValueError("null question embedding")

        raw_embs = await asyncio.gather(
            *[
                self._embed.embed_text_safe(c["text"][:CHUNK_TEXT_LIMIT])
                for c in self._context
            ],
            return_exceptions=True,
        )

        valid_pairs = []
        for emb, chunk in zip(raw_embs, self._context):
            if isinstance(emb, list) and emb is not None:
                valid_pairs.append((emb, chunk))

        if not valid_pairs:
            return sorted(self._context, key=lambda x: x["score"], reverse=True)[
                :MAX_CONTEXT_CHUNKS
            ]

        chunk_embs, chunks = zip(*valid_pairs)
        q_arr  = np.array(q_emb).reshape(1, -1)
        c_arr  = np.array(chunk_embs)
        scores = cosine_similarity(q_arr, c_arr).flatten()
        top_indices = scores.argsort()[::-1][:MAX_CONTEXT_CHUNKS]
        return [chunks[i] for i in top_indices]

    def _format_history(self) -> str:
        if not self._history:
            return "(no previous turns)"
        parts = []
        for q, a in self._history[-MAX_HISTORY_TURNS:]:
            truncated = textwrap.shorten(a, width=300, placeholder="…")
            parts.append(f"User: {q}\nAssistant: {truncated}")
        return "\n\n".join(parts)