"""
qa_assistant.py — Source-Grounded Q&A Assistant  v1.0

Provides a conversational Q&A interface where every answer is:
  1. Generated by Groq (llama-3.3-70b) with the retrieved context injected.
  2. Grounded in the validated sources from the last discovery session.
  3. Annotated with inline citations [1], [2], … linked to PMIDs / URLs.
  4. Refused if the answer cannot be grounded (hallucination guard).

Usage:
    qa = QAAssistant(groq_client, embed_service, qdrant_mgr)
    await qa.load_session(response)          # load context from ACPResponse
    answer = await qa.ask("What is the IC50 of Sotorasib against KRAS G12C?")
    print(answer.text)
    for ref in answer.references:
        print(ref)

The assistant maintains a short conversation history (last 6 turns) so
follow-up questions work naturally.
"""

from __future__ import annotations

import asyncio
import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

from loguru import logger

from models import ACPResponse


# =============================================================================
# DATA MODELS
# =============================================================================

@dataclass
class Reference:
    index:    int
    title:    str
    url:      str
    pmid:     Optional[str] = None
    doi:      Optional[str] = None
    domain:   str           = ""

    def __str__(self) -> str:
        pmid_str = f" (PMID:{self.pmid})" if self.pmid else ""
        return f"[{self.index}] {self.title}{pmid_str} — {self.url}"


@dataclass
class QAAnswer:
    question:   str
    text:       str                      # answer with [N] inline citations
    references: List[Reference]          # numbered reference list
    grounded:   bool  = True             # False if hallucination guard triggered
    sources_used: int = 0

    def to_text(self) -> str:
        """Plain-text rendering with reference list appended."""
        ref_block = "\n".join(str(r) for r in self.references)
        suffix = f"\n\n**References:**\n{ref_block}" if self.references else ""
        if not self.grounded:
            suffix = "\n\n⚠ *This answer could not be fully grounded in the available sources.*"
        return self.text + suffix


# =============================================================================
# PROMPTS
# =============================================================================

_QA_SYSTEM = """\
You are a rigorous biomedical research assistant. You ONLY answer from the
provided context sources. For every factual claim, add an inline citation
like [1] or [2] referring to the numbered sources below.

Rules:
- Use ONLY information from the provided sources — do NOT add outside knowledge.
- If the answer is not in the sources, reply ONLY:
  "INSUFFICIENT_CONTEXT: <brief explanation>"
- Keep answers concise (≤250 words unless the question requires more).
- Use markdown for clarity (bold key terms, bullet points for lists).
- Never fabricate PMIDs, DOIs, or drug names.
"""

_QA_USER_TEMPLATE = """\
SOURCES:
{sources}

CONVERSATION HISTORY:
{history}

QUESTION: {question}

Answer with inline citations [N]. If you cannot answer from these sources,
respond with INSUFFICIENT_CONTEXT.
"""


# =============================================================================
# QA ASSISTANT
# =============================================================================

class QAAssistant:
    """
    Source-grounded Q&A assistant for drug target discovery sessions.

    Retrieves the most relevant context chunks from Qdrant for each question,
    then prompts Groq with those chunks + conversation history.
    """

    MAX_HISTORY_TURNS = 6
    MAX_CONTEXT_CHUNKS = 8

    def __init__(self, groq_client, embed_service, qdrant_mgr):
        self._groq      = groq_client
        self._embed     = embed_service
        self._qdrant    = qdrant_mgr
        self._context:  List[Dict[str, Any]] = []  # flat source dicts from last session
        self._history:  List[Tuple[str, str]] = []  # (question, answer) pairs

    # =========================================================================
    # SESSION MANAGEMENT
    # =========================================================================

    def load_session(self, response: ACPResponse) -> None:
        """
        Load context from a completed ACPResponse.
        Flattens payload items + enriches with target/chemical data.
        """
        self._context = []
        self._history = []

        # Source documents
        for items in response.payload.values():
            for item in items:
                self._context.append({
                    "title":  item.get("title", "Untitled"),
                    "url":    item.get("source_url", ""),
                    "pmid":   item.get("pmid"),
                    "doi":    item.get("doi"),
                    "text":   item.get("content", "")[:600],
                    "score":  item.get("validation_score", 0.0),
                })

        # Synthesised target summaries
        for t in response.targets or []:
            summary = (
                f"Drug target: {t.get('gene','?')} ({t.get('protein','')}) "
                f"| Disease: {t.get('disease_context','?')} "
                f"| UniProt: {t.get('uniprot_id','?')} "
                f"| Mutations: {', '.join(t.get('mutations',[]))} "
                f"| Druggability: {t.get('druggability_notes','')[:120]} "
                f"| PubMed freq score: {t.get('pubmed_frequency_score','?')} "
                f"| Top pathway: {t.get('top_pathway','?')}"
            )
            self._context.append({
                "title": f"Target: {t.get('gene','?')}",
                "url":   f"https://uniprot.org/uniprot/{t.get('uniprot_id','')}",
                "pmid":  (t.get("supporting_pmids") or [None])[0],
                "doi":   None,
                "text":  summary,
                "score": 0.95,
            })

        # Synthesised chemical summaries
        for c in response.chemicals or []:
            acts = c.get("bioactivities", [])
            act_str = "; ".join(
                f"{a.get('target','?')} {a.get('assay_type','?')} "
                f"{a.get('relation','=')}{a.get('value','?')} {a.get('units','?')}"
                for a in acts[:3]
            )
            summary = (
                f"Chemical: {c.get('name','?')} | Formula: {c.get('formula','?')} "
                f"| MW: {c.get('mol_weight','?')} Da "
                f"| Phase: {c.get('phase','?')} "
                f"| Class: {c.get('drug_class','?')} "
                f"| Bioactivity: {act_str or 'none'}"
            )
            self._context.append({
                "title": f"Chemical: {c.get('name','?')}",
                "url":   c.get("pubchem_url", ""),
                "pmid":  (c.get("supporting_pmids") or [None])[0],
                "doi":   None,
                "text":  summary,
                "score": 0.90,
            })

        logger.info(
            f"QAAssistant: loaded {len(self._context)} context chunks "
            f"from session {response.session_id}"
        )

    # =========================================================================
    # ASK
    # =========================================================================

    async def ask(self, question: str) -> QAAnswer:
        if not self._context:
            return QAAnswer(
                question=question,
                text="No discovery session is loaded. Run a query first.",
                references=[],
                grounded=False,
            )

        # ── Select most relevant context via semantic search ──────────────────
        relevant = await self._select_context(question)
        if not relevant:
            relevant = sorted(self._context, key=lambda x: x["score"], reverse=True)[
                : self.MAX_CONTEXT_CHUNKS
            ]

        # ── Build numbered source block ────────────────────────────────────────
        source_block = self._format_sources(relevant)

        # ── Build history block ────────────────────────────────────────────────
        history_block = self._format_history()

        prompt = _QA_USER_TEMPLATE.format(
            sources=source_block,
            history=history_block,
            question=question,
        )

        # ── Call Groq ─────────────────────────────────────────────────────────
        raw = ""
        if self._groq is not None:
            try:
                raw = await self._groq.chat(
                    prompt,
                    max_tokens=600,
                    temperature=0.0,
                    system_prompt=_QA_SYSTEM,
                )
            except Exception as exc:
                logger.warning(f"QAAssistant Groq call failed: {exc}")

        # ── Hallucination guard ───────────────────────────────────────────────
        grounded = True
        if not raw or raw.strip().startswith("INSUFFICIENT_CONTEXT"):
            reason = raw.replace("INSUFFICIENT_CONTEXT:", "").strip() if raw else "Groq unavailable"
            grounded = False
            answer_text = (
                "I cannot find a reliable answer to this question in the available "
                f"sources. {reason}\n\n"
                "You may want to run a more specific query or check the original sources."
            )
            references: List[Reference] = []
        else:
            answer_text, references = self._parse_citations(raw, relevant)

        # ── Update history ────────────────────────────────────────────────────
        self._history.append((question, answer_text))
        if len(self._history) > self.MAX_HISTORY_TURNS:
            self._history = self._history[-self.MAX_HISTORY_TURNS:]

        return QAAnswer(
            question=question,
            text=answer_text,
            references=references,
            grounded=grounded,
            sources_used=len(relevant),
        )

    def clear_history(self) -> None:
        """Reset conversation history (keep session context)."""
        self._history = []

    def context_count(self) -> int:
        return len(self._context)

    # =========================================================================
    # PRIVATE HELPERS
    # =========================================================================

    async def _select_context(
        self, question: str
    ) -> List[Dict[str, Any]]:
        """
        Use semantic similarity (via EmbeddingService) to pick the most
        relevant context chunks.  Falls back to score-sorted order if
        embedding fails.
        """
        try:
            q_emb = await self._embed.embed_text_safe(question)
            if q_emb is None:
                raise ValueError("null embedding")

            import numpy as np
            from sklearn.metrics.pairwise import cosine_similarity

            texts = [c["text"] for c in self._context]
            # Embed in batches to avoid huge allocations
            chunk_embs = []
            loop = asyncio.get_running_loop()
            for text in texts:
                emb = await self._embed.embed_text_safe(text[:400])
                chunk_embs.append(emb if emb is not None else [0.0] * len(q_emb))

            q_arr    = np.array(q_emb).reshape(1, -1)
            c_arr    = np.array(chunk_embs)
            scores   = cosine_similarity(q_arr, c_arr).flatten()
            top_idx  = scores.argsort()[::-1][: self.MAX_CONTEXT_CHUNKS]
            return [self._context[i] for i in top_idx]
        except Exception as exc:
            logger.debug(f"QA context selection failed: {exc} — using score order")
            return sorted(self._context, key=lambda x: x["score"], reverse=True)[
                : self.MAX_CONTEXT_CHUNKS
            ]

    @staticmethod
    def _format_sources(chunks: List[Dict[str, Any]]) -> str:
        lines = []
        for i, c in enumerate(chunks, 1):
            pmid_str = f" | PMID:{c['pmid']}" if c.get("pmid") else ""
            lines.append(
                f"[{i}] {c['title']}{pmid_str}\n"
                f"URL: {c['url']}\n"
                f"{c['text']}\n"
            )
        return "\n---\n".join(lines)

    def _format_history(self) -> str:
        if not self._history:
            return "(no previous turns)"
        parts = []
        for q, a in self._history[-4:]:
            parts.append(f"User: {q}\nAssistant: {a[:300]}…")
        return "\n\n".join(parts)

    @staticmethod
    def _parse_citations(
        raw: str, chunks: List[Dict[str, Any]]
    ) -> Tuple[str, List[Reference]]:
        """
        Extract [N] citation markers from raw Groq output and build
        a deduplicated Reference list.
        """
        cited_indices = sorted(set(int(m) for m in re.findall(r"\[(\d+)\]", raw)))
        references: List[Reference] = []
        for idx in cited_indices:
            if 1 <= idx <= len(chunks):
                c = chunks[idx - 1]
                references.append(Reference(
                    index=idx,
                    title=c.get("title", "Untitled"),
                    url=c.get("url", ""),
                    pmid=c.get("pmid"),
                    doi=c.get("doi"),
                ))
        return raw, references